apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudbrain

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - prometheus.yaml
  - deployments.yaml
  - services.yaml
  - traffic-generator.yaml
  - ingress.yaml
